//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 02:47:48 PM EST 
//


package au.csiro.casda.votools.jaxb.tapregext;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *       Limits on data sizes, given in rows or bytes.
 *       
 * 
 * <p>Java class for DataLimits complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataLimits">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="default" type="{http://www.ivoa.net/xml/TAPRegExt/v1.0}DataLimit" minOccurs="0"/>
 *         &lt;element name="hard" type="{http://www.ivoa.net/xml/TAPRegExt/v1.0}DataLimit" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataLimits", propOrder = {
    "_default",
    "hard"
})
public class DataLimits {

    @XmlElement(name = "default")
    protected DataLimit _default;
    protected DataLimit hard;

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link DataLimit }
     *     
     */
    public DataLimit getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataLimit }
     *     
     */
    public void setDefault(DataLimit value) {
        this._default = value;
    }

    /**
     * Gets the value of the hard property.
     * 
     * @return
     *     possible object is
     *     {@link DataLimit }
     *     
     */
    public DataLimit getHard() {
        return hard;
    }

    /**
     * Sets the value of the hard property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataLimit }
     *     
     */
    public void setHard(DataLimit value) {
        this.hard = value;
    }

}
