//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 02:47:48 PM EST 
//


package au.csiro.casda.votools.jaxb.tapregext;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.csiro.casda.votools.jaxb.tapregext package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.csiro.casda.votools.jaxb.tapregext
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LanguageFeature }
     * 
     */
    public LanguageFeature createLanguageFeature() {
        return new LanguageFeature();
    }

    /**
     * Create an instance of {@link TableAccess }
     * 
     */
    public TableAccess createTableAccess() {
        return new TableAccess();
    }

    /**
     * Create an instance of {@link OutputFormat }
     * 
     */
    public OutputFormat createOutputFormat() {
        return new OutputFormat();
    }

    /**
     * Create an instance of {@link DataLimit }
     * 
     */
    public DataLimit createDataLimit() {
        return new DataLimit();
    }

    /**
     * Create an instance of {@link TimeLimits }
     * 
     */
    public TimeLimits createTimeLimits() {
        return new TimeLimits();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link DataModelType }
     * 
     */
    public DataModelType createDataModelType() {
        return new DataModelType();
    }

    /**
     * Create an instance of {@link UploadMethod }
     * 
     */
    public UploadMethod createUploadMethod() {
        return new UploadMethod();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link DataLimits }
     * 
     */
    public DataLimits createDataLimits() {
        return new DataLimits();
    }

    /**
     * Create an instance of {@link LanguageFeatureList }
     * 
     */
    public LanguageFeatureList createLanguageFeatureList() {
        return new LanguageFeatureList();
    }

}
