//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 02:47:48 PM EST 
//


package au.csiro.casda.votools.jaxb.tapregext;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *       The capabilities attempt to define most issues that the
 *       TAP standard leaves to the implementors ("may", "should").
 *       
 * 
 * <p>Java class for TableAccess complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TableAccess">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/TAPRegExt/v1.0}TAPCapRestriction">
 *       &lt;sequence>
 *         &lt;element name="dataModel" type="{http://www.ivoa.net/xml/TAPRegExt/v1.0}DataModelType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="language" type="{http://www.ivoa.net/xml/TAPRegExt/v1.0}Language" maxOccurs="unbounded"/>
 *         &lt;element name="outputFormat" type="{http://www.ivoa.net/xml/TAPRegExt/v1.0}OutputFormat" maxOccurs="unbounded"/>
 *         &lt;element name="uploadMethod" type="{http://www.ivoa.net/xml/TAPRegExt/v1.0}UploadMethod" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="retentionPeriod" type="{http://www.ivoa.net/xml/TAPRegExt/v1.0}TimeLimits" minOccurs="0"/>
 *         &lt;element name="executionDuration" type="{http://www.ivoa.net/xml/TAPRegExt/v1.0}TimeLimits" minOccurs="0"/>
 *         &lt;element name="outputLimit" type="{http://www.ivoa.net/xml/TAPRegExt/v1.0}DataLimits" minOccurs="0"/>
 *         &lt;element name="uploadLimit" type="{http://www.ivoa.net/xml/TAPRegExt/v1.0}DataLimits" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TableAccess", propOrder = {
    "dataModel",
    "language",
    "outputFormat",
    "uploadMethod",
    "retentionPeriod",
    "executionDuration",
    "outputLimit",
    "uploadLimit"
})
public class TableAccess
    extends TAPCapRestriction
{

    protected List<DataModelType> dataModel;
    @XmlElement(required = true)
    protected List<Language> language;
    @XmlElement(required = true)
    protected List<OutputFormat> outputFormat;
    protected List<UploadMethod> uploadMethod;
    protected TimeLimits retentionPeriod;
    protected TimeLimits executionDuration;
    protected DataLimits outputLimit;
    protected DataLimits uploadLimit;

    /**
     * Gets the value of the dataModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataModelType }
     * 
     * 
     */
    public List<DataModelType> getDataModel() {
        if (dataModel == null) {
            dataModel = new ArrayList<DataModelType>();
        }
        return this.dataModel;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Language }
     * 
     * 
     */
    public List<Language> getLanguage() {
        if (language == null) {
            language = new ArrayList<Language>();
        }
        return this.language;
    }

    /**
     * Gets the value of the outputFormat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputFormat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutputFormat }
     * 
     * 
     */
    public List<OutputFormat> getOutputFormat() {
        if (outputFormat == null) {
            outputFormat = new ArrayList<OutputFormat>();
        }
        return this.outputFormat;
    }

    /**
     * Gets the value of the uploadMethod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uploadMethod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUploadMethod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UploadMethod }
     * 
     * 
     */
    public List<UploadMethod> getUploadMethod() {
        if (uploadMethod == null) {
            uploadMethod = new ArrayList<UploadMethod>();
        }
        return this.uploadMethod;
    }

    /**
     * Gets the value of the retentionPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link TimeLimits }
     *     
     */
    public TimeLimits getRetentionPeriod() {
        return retentionPeriod;
    }

    /**
     * Sets the value of the retentionPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeLimits }
     *     
     */
    public void setRetentionPeriod(TimeLimits value) {
        this.retentionPeriod = value;
    }

    /**
     * Gets the value of the executionDuration property.
     * 
     * @return
     *     possible object is
     *     {@link TimeLimits }
     *     
     */
    public TimeLimits getExecutionDuration() {
        return executionDuration;
    }

    /**
     * Sets the value of the executionDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeLimits }
     *     
     */
    public void setExecutionDuration(TimeLimits value) {
        this.executionDuration = value;
    }

    /**
     * Gets the value of the outputLimit property.
     * 
     * @return
     *     possible object is
     *     {@link DataLimits }
     *     
     */
    public DataLimits getOutputLimit() {
        return outputLimit;
    }

    /**
     * Sets the value of the outputLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataLimits }
     *     
     */
    public void setOutputLimit(DataLimits value) {
        this.outputLimit = value;
    }

    /**
     * Gets the value of the uploadLimit property.
     * 
     * @return
     *     possible object is
     *     {@link DataLimits }
     *     
     */
    public DataLimits getUploadLimit() {
        return uploadLimit;
    }

    /**
     * Sets the value of the uploadLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataLimits }
     *     
     */
    public void setUploadLimit(DataLimits value) {
        this.uploadLimit = value;
    }

}
