//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:45:57 PM EST 
//


package au.csiro.casda.votools.jaxb.vodataservice;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import au.csiro.casda.votools.jaxb.stc.AstroSTCDescriptionType;


/**
 * 
 *            A description of how a resource's contents or behavior maps
 *            to the sky, to time, and to frequency space, including
 *            coverage and resolution. 
 *          
 * 
 * <p>Java class for Coverage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Coverage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}STCResourceProfile" minOccurs="0"/>
 *         &lt;element name="footprint" type="{http://www.ivoa.net/xml/VODataService/v1.1}ServiceReference" minOccurs="0"/>
 *         &lt;element name="waveband" type="{http://www.ivoa.net/xml/VODataService/v1.1}Waveband" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="regionOfRegard" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Coverage", propOrder = {
    "stcResourceProfile",
    "footprint",
    "waveband",
    "regionOfRegard"
})
public class Coverage {

    @XmlElement(name = "STCResourceProfile", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", nillable = true)
    protected AstroSTCDescriptionType stcResourceProfile;
    protected ServiceReference footprint;
    protected List<Waveband> waveband;
    protected Float regionOfRegard;

    /**
     * 
     *                  In general, this description should be approximate; a
     *                  more precise description can be provided by the 
     *                  footprint service.  
     *                
     * 
     * @return
     *     possible object is
     *     {@link AstroSTCDescriptionType }
     *     
     */
    public AstroSTCDescriptionType getSTCResourceProfile() {
        return stcResourceProfile;
    }

    /**
     * Sets the value of the stcResourceProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link AstroSTCDescriptionType }
     *     
     */
    public void setSTCResourceProfile(AstroSTCDescriptionType value) {
        this.stcResourceProfile = value;
    }

    /**
     * Gets the value of the footprint property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceReference }
     *     
     */
    public ServiceReference getFootprint() {
        return footprint;
    }

    /**
     * Sets the value of the footprint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceReference }
     *     
     */
    public void setFootprint(ServiceReference value) {
        this.footprint = value;
    }

    /**
     * Gets the value of the waveband property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the waveband property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWaveband().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Waveband }
     * 
     * 
     */
    public List<Waveband> getWaveband() {
        if (waveband == null) {
            waveband = new ArrayList<Waveband>();
        }
        return this.waveband;
    }

    /**
     * Gets the value of the regionOfRegard property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRegionOfRegard() {
        return regionOfRegard;
    }

    /**
     * Sets the value of the regionOfRegard property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRegionOfRegard(Float value) {
        this.regionOfRegard = value;
    }

}
