//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:45:57 PM EST 
//


package au.csiro.casda.votools.jaxb.vodataservice;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import au.csiro.casda.votools.jaxb.voresource.AccessURL;
import au.csiro.casda.votools.jaxb.voresource.Resource;
import au.csiro.casda.votools.jaxb.voresource.ResourceName;
import au.csiro.casda.votools.jaxb.voresource.Rights;


/**
 * 
 *            (A dataset is a collection of digitally-encoded data that 
 *            is normally accessible as a single unit, e.g. a file.)
 *          
 * 
 * <p>Java class for DataCollection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataCollection">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VOResource/v1.0}Resource">
 *       &lt;sequence>
 *         &lt;element name="facility" type="{http://www.ivoa.net/xml/VOResource/v1.0}ResourceName" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="instrument" type="{http://www.ivoa.net/xml/VOResource/v1.0}ResourceName" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rights" type="{http://www.ivoa.net/xml/VOResource/v1.0}Rights" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="format" type="{http://www.ivoa.net/xml/VODataService/v1.1}Format" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="coverage" type="{http://www.ivoa.net/xml/VODataService/v1.1}Coverage" minOccurs="0"/>
 *         &lt;element name="tableset" type="{http://www.ivoa.net/xml/VODataService/v1.1}TableSet" minOccurs="0"/>
 *         &lt;element name="accessURL" type="{http://www.ivoa.net/xml/VOResource/v1.0}AccessURL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataCollection", propOrder = {
    "facility",
    "instrument",
    "rights",
    "format",
    "coverage",
    "tableset",
    "accessURL"
})
public class DataCollection
    extends Resource
{

    protected List<ResourceName> facility;
    protected List<ResourceName> instrument;
    protected List<Rights> rights;
    protected List<Format> format;
    protected Coverage coverage;
    protected TableSet tableset;
    protected AccessURL accessURL;

    /**
     * Gets the value of the facility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the facility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFacility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceName }
     * 
     * 
     */
    public List<ResourceName> getFacility() {
        if (facility == null) {
            facility = new ArrayList<ResourceName>();
        }
        return this.facility;
    }

    /**
     * Gets the value of the instrument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instrument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstrument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceName }
     * 
     * 
     */
    public List<ResourceName> getInstrument() {
        if (instrument == null) {
            instrument = new ArrayList<ResourceName>();
        }
        return this.instrument;
    }

    /**
     * Gets the value of the rights property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rights property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRights().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rights }
     * 
     * 
     */
    public List<Rights> getRights() {
        if (rights == null) {
            rights = new ArrayList<Rights>();
        }
        return this.rights;
    }

    /**
     * Gets the value of the format property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the format property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Format }
     * 
     * 
     */
    public List<Format> getFormat() {
        if (format == null) {
            format = new ArrayList<Format>();
        }
        return this.format;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link Coverage }
     *     
     */
    public Coverage getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coverage }
     *     
     */
    public void setCoverage(Coverage value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the tableset property.
     * 
     * @return
     *     possible object is
     *     {@link TableSet }
     *     
     */
    public TableSet getTableset() {
        return tableset;
    }

    /**
     * Sets the value of the tableset property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableSet }
     *     
     */
    public void setTableset(TableSet value) {
        this.tableset = value;
    }

    /**
     * Gets the value of the accessURL property.
     * 
     * @return
     *     possible object is
     *     {@link AccessURL }
     *     
     */
    public AccessURL getAccessURL() {
        return accessURL;
    }

    /**
     * Sets the value of the accessURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessURL }
     *     
     */
    public void setAccessURL(AccessURL value) {
        this.accessURL = value;
    }

}
