//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:45:57 PM EST 
//


package au.csiro.casda.votools.jaxb.vodataservice;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             The allowed data type names do not imply a size or precise
 *             format.  This type is intended to be sufficient for describing
 *             an input parameter to a simple REST service or a function 
 *             written in a weakly-typed (e.g., scripting) language.
 *          
 * 
 * <p>Java class for InputParam complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InputParam">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VODataService/v1.1}BaseParam">
 *       &lt;sequence>
 *         &lt;element name="dataType" type="{http://www.ivoa.net/xml/VODataService/v1.1}SimpleDataType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="use" type="{http://www.ivoa.net/xml/VODataService/v1.1}ParamUse" default="optional" />
 *       &lt;attribute name="std" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InputParam", propOrder = {
    "dataType"
})
public class InputParam
    extends BaseParam
{

    protected SimpleDataType dataType;
    @XmlAttribute(name = "use")
    protected ParamUse use;
    @XmlAttribute(name = "std")
    protected Boolean std;

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleDataType }
     *     
     */
    public SimpleDataType getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleDataType }
     *     
     */
    public void setDataType(SimpleDataType value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the use property.
     * 
     * @return
     *     possible object is
     *     {@link ParamUse }
     *     
     */
    public ParamUse getUse() {
        if (use == null) {
            return ParamUse.OPTIONAL;
        } else {
            return use;
        }
    }

    /**
     * Sets the value of the use property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamUse }
     *     
     */
    public void setUse(ParamUse value) {
        this.use = value;
    }

    /**
     * Gets the value of the std property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isStd() {
        if (std == null) {
            return true;
        } else {
            return std;
        }
    }

    /**
     * Sets the value of the std property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStd(Boolean value) {
        this.std = value;
    }

}
