//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:45:57 PM EST 
//


package au.csiro.casda.votools.jaxb.vodataservice;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import au.csiro.casda.votools.jaxb.stc.AstroSTCDescriptionType;
import au.csiro.casda.votools.jaxb.stc.StcMetadataType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.csiro.casda.votools.jaxb.vodataservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _STCmetadata_QNAME = new QName("http://www.ivoa.net/xml/STC/stc-v1.30.xsd", "STCmetadata");
    private final static QName _STCResourceProfile_QNAME = new QName("http://www.ivoa.net/xml/STC/stc-v1.30.xsd", "STCResourceProfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.csiro.casda.votools.jaxb.vodataservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Format }
     * 
     */
    public Format createFormat() {
        return new Format();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link BaseParam }
     * 
     */
    public BaseParam createBaseParam() {
        return new BaseParam();
    }

    /**
     * Create an instance of {@link TAPType }
     * 
     */
    public TAPType createTAPType() {
        return new TAPType();
    }

    /**
     * Create an instance of {@link Coverage }
     * 
     */
    public Coverage createCoverage() {
        return new Coverage();
    }

    /**
     * Create an instance of {@link SimpleDataType }
     * 
     */
    public SimpleDataType createSimpleDataType() {
        return new SimpleDataType();
    }

    /**
     * Create an instance of {@link FKColumn }
     * 
     */
    public FKColumn createFKColumn() {
        return new FKColumn();
    }

    /**
     * Create an instance of {@link TableSet }
     * 
     */
    public TableSet createTableSet() {
        return new TableSet();
    }

    /**
     * Create an instance of {@link InputParam }
     * 
     */
    public InputParam createInputParam() {
        return new InputParam();
    }

    /**
     * Create an instance of {@link StandardSTC }
     * 
     */
    public StandardSTC createStandardSTC() {
        return new StandardSTC();
    }

    /**
     * Create an instance of {@link TableParam }
     * 
     */
    public TableParam createTableParam() {
        return new TableParam();
    }

    /**
     * Create an instance of {@link VOTableType }
     * 
     */
    public VOTableType createVOTableType() {
        return new VOTableType();
    }

    /**
     * Create an instance of {@link CatalogService }
     * 
     */
    public CatalogService createCatalogService() {
        return new CatalogService();
    }

    /**
     * Create an instance of {@link ParamHTTP }
     * 
     */
    public ParamHTTP createParamHTTP() {
        return new ParamHTTP();
    }

    /**
     * Create an instance of {@link TableSchema }
     * 
     */
    public TableSchema createTableSchema() {
        return new TableSchema();
    }

    /**
     * Create an instance of {@link ServiceReference }
     * 
     */
    public ServiceReference createServiceReference() {
        return new ServiceReference();
    }

    /**
     * Create an instance of {@link ForeignKey }
     * 
     */
    public ForeignKey createForeignKey() {
        return new ForeignKey();
    }

    /**
     * Create an instance of {@link DataCollection }
     * 
     */
    public DataCollection createDataCollection() {
        return new DataCollection();
    }

    /**
     * Create an instance of {@link DataService }
     * 
     */
    public DataService createDataService() {
        return new DataService();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StcMetadataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", name = "STCmetadata")
    public JAXBElement<StcMetadataType> createSTCmetadata(StcMetadataType value) {
        return new JAXBElement<StcMetadataType>(_STCmetadata_QNAME, StcMetadataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AstroSTCDescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", name = "STCResourceProfile", substitutionHeadNamespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", substitutionHeadName = "STCmetadata")
    public JAXBElement<AstroSTCDescriptionType> createSTCResourceProfile(AstroSTCDescriptionType value) {
        return new JAXBElement<AstroSTCDescriptionType>(_STCResourceProfile_QNAME, AstroSTCDescriptionType.class, null, value);
    }

}
