//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:45:57 PM EST 
//


package au.csiro.casda.votools.jaxb.vodataservice;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import au.csiro.casda.votools.jaxb.stc.StcDescriptionType;
import au.csiro.casda.votools.jaxb.voresource.Resource;


/**
 * 
 *            This resource provides a mechanism for registering standard 
 *            coordinate systems which other resources may reference as
 *            part of a coverage descripiton.  In particular, coverage
 *            descriptions will refer to components of the STC
 *            descriptions in this resource via an IVOA identifier.  It
 *            is intended that an application consuming such coverage
 *            descriptions be able to semantically interpret the
 *            identifier without resolving it.  For this reason, once a
 *            standard STC description is registered with this resource 
 *            type, updating the description is strongly discouraged.  
 *          
 * 
 * <p>Java class for StandardSTC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StandardSTC">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VOResource/v1.0}Resource">
 *       &lt;sequence>
 *         &lt;element name="stcDefinitions" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}stcDescriptionType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StandardSTC", propOrder = {
    "stcDefinitions"
})
public class StandardSTC
    extends Resource
{

    @XmlElement(required = true)
    protected List<StcDescriptionType> stcDefinitions;

    /**
     * Gets the value of the stcDefinitions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stcDefinitions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStcDefinitions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StcDescriptionType }
     * 
     * 
     */
    public List<StcDescriptionType> getStcDefinitions() {
        if (stcDefinitions == null) {
            stcDefinitions = new ArrayList<StcDescriptionType>();
        }
        return this.stcDefinitions;
    }

}
