//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:39:04 PM EST 
//


package au.csiro.casda.votools.jaxb.stc;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Coordinate references to a specific FITS file
 * 
 * Coordinate references to a specific FITS file
 * 
 * <p>Java class for astroCoordsFileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="astroCoordsFileType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordinateType">
 *       &lt;sequence>
 *         &lt;element name="FITSFile" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}fitsType"/>
 *         &lt;element name="FITSTime" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordFITSColumnsType" minOccurs="0"/>
 *         &lt;element name="FITSPosition" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordFITSColumnsType" minOccurs="0"/>
 *         &lt;element name="FITSVelocity" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordFITSColumnsType" minOccurs="0"/>
 *         &lt;element name="FITSSpectral" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordFITSColumnsType" minOccurs="0"/>
 *         &lt;element name="FITSRedshift" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordFITSColumnsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "astroCoordsFileType", propOrder = {
    "fitsFile",
    "fitsTime",
    "fitsPosition",
    "fitsVelocity",
    "fitsSpectral",
    "fitsRedshift"
})
public class AstroCoordsFileType
    extends CoordinateType
{

    @XmlElement(name = "FITSFile", required = true)
    protected FitsType fitsFile;
    @XmlElement(name = "FITSTime")
    protected CoordFITSColumnsType fitsTime;
    @XmlElement(name = "FITSPosition")
    protected CoordFITSColumnsType fitsPosition;
    @XmlElement(name = "FITSVelocity")
    protected CoordFITSColumnsType fitsVelocity;
    @XmlElement(name = "FITSSpectral")
    protected CoordFITSColumnsType fitsSpectral;
    @XmlElement(name = "FITSRedshift")
    protected CoordFITSColumnsType fitsRedshift;

    /**
     * Gets the value of the fitsFile property.
     * 
     * @return
     *     possible object is
     *     {@link FitsType }
     *     
     */
    public FitsType getFITSFile() {
        return fitsFile;
    }

    /**
     * Sets the value of the fitsFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link FitsType }
     *     
     */
    public void setFITSFile(FitsType value) {
        this.fitsFile = value;
    }

    /**
     * Gets the value of the fitsTime property.
     * 
     * @return
     *     possible object is
     *     {@link CoordFITSColumnsType }
     *     
     */
    public CoordFITSColumnsType getFITSTime() {
        return fitsTime;
    }

    /**
     * Sets the value of the fitsTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordFITSColumnsType }
     *     
     */
    public void setFITSTime(CoordFITSColumnsType value) {
        this.fitsTime = value;
    }

    /**
     * Gets the value of the fitsPosition property.
     * 
     * @return
     *     possible object is
     *     {@link CoordFITSColumnsType }
     *     
     */
    public CoordFITSColumnsType getFITSPosition() {
        return fitsPosition;
    }

    /**
     * Sets the value of the fitsPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordFITSColumnsType }
     *     
     */
    public void setFITSPosition(CoordFITSColumnsType value) {
        this.fitsPosition = value;
    }

    /**
     * Gets the value of the fitsVelocity property.
     * 
     * @return
     *     possible object is
     *     {@link CoordFITSColumnsType }
     *     
     */
    public CoordFITSColumnsType getFITSVelocity() {
        return fitsVelocity;
    }

    /**
     * Sets the value of the fitsVelocity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordFITSColumnsType }
     *     
     */
    public void setFITSVelocity(CoordFITSColumnsType value) {
        this.fitsVelocity = value;
    }

    /**
     * Gets the value of the fitsSpectral property.
     * 
     * @return
     *     possible object is
     *     {@link CoordFITSColumnsType }
     *     
     */
    public CoordFITSColumnsType getFITSSpectral() {
        return fitsSpectral;
    }

    /**
     * Sets the value of the fitsSpectral property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordFITSColumnsType }
     *     
     */
    public void setFITSSpectral(CoordFITSColumnsType value) {
        this.fitsSpectral = value;
    }

    /**
     * Gets the value of the fitsRedshift property.
     * 
     * @return
     *     possible object is
     *     {@link CoordFITSColumnsType }
     *     
     */
    public CoordFITSColumnsType getFITSRedshift() {
        return fitsRedshift;
    }

    /**
     * Sets the value of the fitsRedshift property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordFITSColumnsType }
     *     
     */
    public void setFITSRedshift(CoordFITSColumnsType value) {
        this.fitsRedshift = value;
    }

}
