//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:39:04 PM EST 
//


package au.csiro.casda.votools.jaxb.stc;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * The astronomical (STC) coordsType
 * 
 * <p>Java class for astroCoordsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="astroCoordsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordsType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}Time" minOccurs="0"/>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}Position" minOccurs="0"/>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}Velocity" minOccurs="0"/>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}Spectral" minOccurs="0"/>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}Redshift" minOccurs="0"/>
 *         &lt;element name="CoordFile" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}astroCoordsFileType" minOccurs="0"/>
 *         &lt;element name="Orbit" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}orbitType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "astroCoordsType", propOrder = {
    "time",
    "position",
    "velocity",
    "spectral",
    "redshift",
    "coordFile",
    "orbit"
})
public class AstroCoordsType
    extends CoordsType
{

    @XmlElement(name = "Time", nillable = true)
    protected TimeCoordinateType time;
    @XmlElementRef(name = "Position", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends CoordinateType> position;
    @XmlElementRef(name = "Velocity", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends CoordinateType> velocity;
    @XmlElement(name = "Spectral", nillable = true)
    protected SpectralCoordinateType spectral;
    @XmlElement(name = "Redshift", nillable = true)
    protected RedshiftCoordinateType redshift;
    @XmlElementRef(name = "CoordFile", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<AstroCoordsFileType> coordFile;
    @XmlElementRef(name = "Orbit", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<OrbitType> orbit;

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link TimeCoordinateType }
     *     
     */
    public TimeCoordinateType getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeCoordinateType }
     *     
     */
    public void setTime(TimeCoordinateType value) {
        this.time = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PosVector3CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PosVector1CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PosVector2CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordinateType }{@code >}
     *     
     */
    public JAXBElement<? extends CoordinateType> getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PosVector3CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PosVector1CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PosVector2CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordinateType }{@code >}
     *     
     */
    public void setPosition(JAXBElement<? extends CoordinateType> value) {
        this.position = value;
    }

    /**
     * Gets the value of the velocity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link VelVector3CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link VelVector2CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link VelVector1CoordinateType }{@code >}
     *     
     */
    public JAXBElement<? extends CoordinateType> getVelocity() {
        return velocity;
    }

    /**
     * Sets the value of the velocity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link VelVector3CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link VelVector2CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link VelVector1CoordinateType }{@code >}
     *     
     */
    public void setVelocity(JAXBElement<? extends CoordinateType> value) {
        this.velocity = value;
    }

    /**
     * Gets the value of the spectral property.
     * 
     * @return
     *     possible object is
     *     {@link SpectralCoordinateType }
     *     
     */
    public SpectralCoordinateType getSpectral() {
        return spectral;
    }

    /**
     * Sets the value of the spectral property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpectralCoordinateType }
     *     
     */
    public void setSpectral(SpectralCoordinateType value) {
        this.spectral = value;
    }

    /**
     * Gets the value of the redshift property.
     * 
     * @return
     *     possible object is
     *     {@link RedshiftCoordinateType }
     *     
     */
    public RedshiftCoordinateType getRedshift() {
        return redshift;
    }

    /**
     * Sets the value of the redshift property.
     * 
     * @param value
     *     allowed object is
     *     {@link RedshiftCoordinateType }
     *     
     */
    public void setRedshift(RedshiftCoordinateType value) {
        this.redshift = value;
    }

    /**
     * Gets the value of the coordFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AstroCoordsFileType }{@code >}
     *     
     */
    public JAXBElement<AstroCoordsFileType> getCoordFile() {
        return coordFile;
    }

    /**
     * Sets the value of the coordFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AstroCoordsFileType }{@code >}
     *     
     */
    public void setCoordFile(JAXBElement<AstroCoordsFileType> value) {
        this.coordFile = value;
    }

    /**
     * Gets the value of the orbit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link OrbitType }{@code >}
     *     
     */
    public JAXBElement<OrbitType> getOrbit() {
        return orbit;
    }

    /**
     * Sets the value of the orbit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link OrbitType }{@code >}
     *     
     */
    public void setOrbit(JAXBElement<OrbitType> value) {
        this.orbit = value;
    }

}
