//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:39:04 PM EST 
//


package au.csiro.casda.votools.jaxb.stc;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * The difference of two regions (Region1 minus Region2) is a region; it is equivalent to the intersection of Region1 with notRegion2
 * 
 * <p>Java class for diffType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="diffType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}regionType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}Region"/>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}Region2"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "diffType", propOrder = {
    "region",
    "region2"
})
public class DiffType
    extends RegionType
{

    @XmlElementRef(name = "Region", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class)
    protected JAXBElement<? extends RegionType> region;
    @XmlElementRef(name = "Region2", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class)
    protected JAXBElement<? extends RegionType> region2;

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link EllipseType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PolygonType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AllSkyType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RegionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CircleType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SkyIndexType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiffType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IntersectionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SectorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConvexHullType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NegationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link UnionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConvexType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BoxType }{@code >}
     *     
     */
    public JAXBElement<? extends RegionType> getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link EllipseType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PolygonType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AllSkyType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RegionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CircleType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SkyIndexType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiffType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IntersectionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SectorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConvexHullType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NegationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link UnionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConvexType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BoxType }{@code >}
     *     
     */
    public void setRegion(JAXBElement<? extends RegionType> value) {
        this.region = value;
    }

    /**
     * Gets the value of the region2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RegionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link EllipseType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConvexHullType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SectorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CircleType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SkyIndexType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PolygonType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConvexType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IntersectionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiffType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BoxType }{@code >}
     *     {@link JAXBElement }{@code <}{@link UnionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NegationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AllSkyType }{@code >}
     *     
     */
    public JAXBElement<? extends RegionType> getRegion2() {
        return region2;
    }

    /**
     * Sets the value of the region2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RegionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link EllipseType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConvexHullType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SectorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CircleType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SkyIndexType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PolygonType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConvexType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IntersectionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiffType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BoxType }{@code >}
     *     {@link JAXBElement }{@code <}{@link UnionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NegationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AllSkyType }{@code >}
     *     
     */
    public void setRegion2(JAXBElement<? extends RegionType> value) {
        this.region2 = value;
    }

}
