//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:39:04 PM EST 
//


package au.csiro.casda.votools.jaxb.stc;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A double with referencing and units attributes
 * 
 * <p>Java class for double1Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="double1Type">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
 *       &lt;attGroup ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}STCReference"/>
 *       &lt;attribute name="time_unit" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}timeUnitType" />
 *       &lt;attribute name="pos_unit" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}posUnitType" />
 *       &lt;attribute name="pos_angle_unit" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}angleUnitType" />
 *       &lt;attribute name="vel_time_unit" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}velTimeUnitType" />
 *       &lt;attribute name="spectral_unit" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}spectralUnitType" />
 *       &lt;attribute name="gen_unit" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}unitType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "double1Type", propOrder = {
    "value"
})
@XmlSeeAlso({
    au.csiro.casda.votools.jaxb.stc.OrbitType.A.class,
    au.csiro.casda.votools.jaxb.stc.OrbitType.Q.class,
    au.csiro.casda.votools.jaxb.stc.OrbitType.I.class,
    au.csiro.casda.votools.jaxb.stc.OrbitType.Node.class,
    au.csiro.casda.votools.jaxb.stc.OrbitType.Aop.class,
    au.csiro.casda.votools.jaxb.stc.OrbitType.M.class,
    au.csiro.casda.votools.jaxb.stc.OrbitType.P.class
})
public class Double1Type {

    @XmlValue
    protected double value;
    @XmlAttribute(name = "time_unit")
    protected String timeUnit;
    @XmlAttribute(name = "pos_unit")
    protected String posUnit;
    @XmlAttribute(name = "pos_angle_unit")
    protected AngleUnitType posAngleUnit;
    @XmlAttribute(name = "vel_time_unit")
    protected VelTimeUnitType velTimeUnit;
    @XmlAttribute(name = "spectral_unit")
    protected SpectralUnitType spectralUnit;
    @XmlAttribute(name = "gen_unit")
    protected String genUnit;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "idref")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object idref;
    @XmlAttribute(name = "ucd")
    protected String ucd;
    @XmlAttribute(name = "type", namespace = "http://www.w3.org/1999/xlink")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "href", namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anyURI")
    protected String href;
    @XmlAttribute(name = "ID_type")
    protected String idType;
    @XmlAttribute(name = "IDREF_type")
    protected String idrefType;

    /**
     * Gets the value of the value property.
     * 
     */
    public double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Gets the value of the timeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeUnit() {
        return timeUnit;
    }

    /**
     * Sets the value of the timeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeUnit(String value) {
        this.timeUnit = value;
    }

    /**
     * Gets the value of the posUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosUnit() {
        return posUnit;
    }

    /**
     * Sets the value of the posUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosUnit(String value) {
        this.posUnit = value;
    }

    /**
     * Gets the value of the posAngleUnit property.
     * 
     * @return
     *     possible object is
     *     {@link AngleUnitType }
     *     
     */
    public AngleUnitType getPosAngleUnit() {
        return posAngleUnit;
    }

    /**
     * Sets the value of the posAngleUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleUnitType }
     *     
     */
    public void setPosAngleUnit(AngleUnitType value) {
        this.posAngleUnit = value;
    }

    /**
     * Gets the value of the velTimeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link VelTimeUnitType }
     *     
     */
    public VelTimeUnitType getVelTimeUnit() {
        return velTimeUnit;
    }

    /**
     * Sets the value of the velTimeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link VelTimeUnitType }
     *     
     */
    public void setVelTimeUnit(VelTimeUnitType value) {
        this.velTimeUnit = value;
    }

    /**
     * Gets the value of the spectralUnit property.
     * 
     * @return
     *     possible object is
     *     {@link SpectralUnitType }
     *     
     */
    public SpectralUnitType getSpectralUnit() {
        return spectralUnit;
    }

    /**
     * Sets the value of the spectralUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpectralUnitType }
     *     
     */
    public void setSpectralUnit(SpectralUnitType value) {
        this.spectralUnit = value;
    }

    /**
     * Gets the value of the genUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenUnit() {
        return genUnit;
    }

    /**
     * Sets the value of the genUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenUnit(String value) {
        this.genUnit = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the idref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIdref() {
        return idref;
    }

    /**
     * Sets the value of the idref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIdref(Object value) {
        this.idref = value;
    }

    /**
     * Gets the value of the ucd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUcd() {
        return ucd;
    }

    /**
     * Sets the value of the ucd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUcd(String value) {
        this.ucd = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "simple";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the idType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDType() {
        return idType;
    }

    /**
     * Sets the value of the idType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDType(String value) {
        this.idType = value;
    }

    /**
     * Gets the value of the idrefType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDREFType() {
        return idrefType;
    }

    /**
     * Sets the value of the idrefType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDREFType(String value) {
        this.idrefType = value;
    }

}
