//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:39:04 PM EST 
//


package au.csiro.casda.votools.jaxb.stc;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 *  2-D Healpix coordinates; defaults for H(4) and K(3)
 * 
 * <p>Java class for healpixType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="healpixType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordFlavorType">
 *       &lt;attribute name="healpix_H" type="{http://www.w3.org/2001/XMLSchema}integer" default="4" />
 *       &lt;attribute name="healpix_K" type="{http://www.w3.org/2001/XMLSchema}integer" default="3" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "healpixType")
public class HealpixType
    extends CoordFlavorType
{

    @XmlAttribute(name = "healpix_H")
    protected BigInteger healpixH;
    @XmlAttribute(name = "healpix_K")
    protected BigInteger healpixK;

    /**
     * Gets the value of the healpixH property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHealpixH() {
        if (healpixH == null) {
            return new BigInteger("4");
        } else {
            return healpixH;
        }
    }

    /**
     * Sets the value of the healpixH property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHealpixH(BigInteger value) {
        this.healpixH = value;
    }

    /**
     * Gets the value of the healpixK property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHealpixK() {
        if (healpixK == null) {
            return new BigInteger("3");
        } else {
            return healpixK;
        }
    }

    /**
     * Sets the value of the healpixK property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHealpixK(BigInteger value) {
        this.healpixK = value;
    }

}
