//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:39:04 PM EST 
//


package au.csiro.casda.votools.jaxb.stc;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Pixel area type
 * 
 * <p>Java class for pixelCoordAreaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pixelCoordAreaType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordAreaType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}PixelCoordInterval"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pixelCoordAreaType", propOrder = {
    "pixelCoordInterval"
})
public class PixelCoordAreaType
    extends CoordAreaType
{

    @XmlElementRef(name = "PixelCoordInterval", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends CoordIntervalType>> pixelCoordInterval;

    /**
     * Gets the value of the pixelCoordInterval property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pixelCoordInterval property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPixelCoordInterval().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link CoordIntervalType }{@code >}
     * {@link JAXBElement }{@code <}{@link Coord3VecIntervalType }{@code >}
     * {@link JAXBElement }{@code <}{@link Coord2VecIntervalType }{@code >}
     * {@link JAXBElement }{@code <}{@link CoordScalarIntervalType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends CoordIntervalType>> getPixelCoordInterval() {
        if (pixelCoordInterval == null) {
            pixelCoordInterval = new ArrayList<JAXBElement<? extends CoordIntervalType>>();
        }
        return this.pixelCoordInterval;
    }

}
