//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:39:04 PM EST 
//


package au.csiro.casda.votools.jaxb.stc;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Element to hold the area of a Region, once calculated; the element holds the actual area, linearAreaUnit the linear units of the of the area (i.e., it should be squared to get the proper units of the area), and validArea indicates whether the area has been calculated properly.
 * 
 * <p>Java class for regionAreaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="regionAreaType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
 *       &lt;attribute name="linearAreaUnit" use="required" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}posUnitType" />
 *       &lt;attribute name="validArea" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "regionAreaType", propOrder = {
    "value"
})
public class RegionAreaType {

    @XmlValue
    protected double value;
    @XmlAttribute(name = "linearAreaUnit", required = true)
    protected String linearAreaUnit;
    @XmlAttribute(name = "validArea", required = true)
    protected boolean validArea;

    /**
     * Gets the value of the value property.
     * 
     */
    public double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Gets the value of the linearAreaUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinearAreaUnit() {
        return linearAreaUnit;
    }

    /**
     * Sets the value of the linearAreaUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinearAreaUnit(String value) {
        this.linearAreaUnit = value;
    }

    /**
     * Gets the value of the validArea property.
     * 
     */
    public boolean isValidArea() {
        return validArea;
    }

    /**
     * Sets the value of the validArea property.
     * 
     */
    public void setValidArea(boolean value) {
        this.validArea = value;
    }

}
