//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:39:04 PM EST 
//


package au.csiro.casda.votools.jaxb.stc;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * A spatial coordinate frame consists of a coordinate frame, a reference position, a flavor, and, optionally, an offset center
 * 
 * <p>Java class for spaceFrameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="spaceFrameType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordFrameType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}SpaceRefFrame"/>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}ReferencePosition"/>
 *         &lt;element name="OffsetCenter" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordValueType" minOccurs="0"/>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}CoordFlavor"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "spaceFrameType", propOrder = {
    "spaceRefFrame",
    "referencePosition",
    "offsetCenter",
    "coordFlavor"
})
public class SpaceFrameType
    extends CoordFrameType
{

    @XmlElementRef(name = "SpaceRefFrame", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class)
    protected JAXBElement<? extends CoordRefFrameType> spaceRefFrame;
    @XmlElementRef(name = "ReferencePosition", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class)
    protected JAXBElement<? extends ReferencePositionType> referencePosition;
    @XmlElement(name = "OffsetCenter")
    protected CoordValueType offsetCenter;
    @XmlElementRef(name = "CoordFlavor", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class)
    protected JAXBElement<? extends CoordFlavorType> coordFlavor;

    /**
     * Coordinate reference frame: optional equinox with either a standard reference system (ICRS, FK5, FK4) and optional standard pole (equatorial, ecliptic, galactic, etc.), or pole (positive Z-axis) and positive X-axis direction 
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Cart3DRefFrameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FkType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordRefFrameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GeodType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SphericalRefFrameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordRefFrameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FkType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Cart1DRefFrameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FkType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Cart2DRefFrameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     
     */
    public JAXBElement<? extends CoordRefFrameType> getSpaceRefFrame() {
        return spaceRefFrame;
    }

    /**
     * Sets the value of the spaceRefFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Cart3DRefFrameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FkType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordRefFrameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GeodType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SphericalRefFrameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordRefFrameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FkType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Cart1DRefFrameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FkType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Cart2DRefFrameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IcrsType }{@code >}
     *     
     */
    public void setSpaceRefFrame(JAXBElement<? extends CoordRefFrameType> value) {
        this.spaceRefFrame = value;
    }

    /**
     * Origin of the coordinate reference frame: either a "known place" such as geocenter or barycenter, or a position defined in a known coordinate system
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CustomRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ReferencePositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     
     */
    public JAXBElement<? extends ReferencePositionType> getReferencePosition() {
        return referencePosition;
    }

    /**
     * Sets the value of the referencePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CustomRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ReferencePositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StdRefPosType }{@code >}
     *     
     */
    public void setReferencePosition(JAXBElement<? extends ReferencePositionType> value) {
        this.referencePosition = value;
    }

    /**
     * Gets the value of the offsetCenter property.
     * 
     * @return
     *     possible object is
     *     {@link CoordValueType }
     *     
     */
    public CoordValueType getOffsetCenter() {
        return offsetCenter;
    }

    /**
     * Sets the value of the offsetCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordValueType }
     *     
     */
    public void setOffsetCenter(CoordValueType value) {
        this.offsetCenter = value;
    }

    /**
     * Provides the coordinate definitions: number of axes, SPHERICAL, CARTESIAN, UNITSPHERE, POLAR, or HEALPIX, presence of velocities
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link HealpixType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     
     */
    public JAXBElement<? extends CoordFlavorType> getCoordFlavor() {
        return coordFlavor;
    }

    /**
     * Sets the value of the coordFlavor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link HealpixType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordFlavorType }{@code >}
     *     
     */
    public void setCoordFlavor(JAXBElement<? extends CoordFlavorType> value) {
        this.coordFlavor = value;
    }

}
