//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:39:04 PM EST 
//


package au.csiro.casda.votools.jaxb.stc;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for timeScaleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="timeScaleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TT"/>
 *     &lt;enumeration value="TDT"/>
 *     &lt;enumeration value="ET"/>
 *     &lt;enumeration value="TDB"/>
 *     &lt;enumeration value="TEB"/>
 *     &lt;enumeration value="TCG"/>
 *     &lt;enumeration value="TCB"/>
 *     &lt;enumeration value="TAI"/>
 *     &lt;enumeration value="IAT"/>
 *     &lt;enumeration value="UTC"/>
 *     &lt;enumeration value="GPS"/>
 *     &lt;enumeration value="LST"/>
 *     &lt;enumeration value="GMST"/>
 *     &lt;enumeration value="LOCAL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "timeScaleType")
@XmlEnum
public enum TimeScaleType {


    /**
     * Terrestrial Time; the basis for ephemerides
     * 
     */
    TT,

    /**
     * Obsolete synonym for TT
     * 
     */
    TDT,

    /**
     * Ephemeris Time; predecessor of, and continuous with, TT
     * 
     */
    ET,

    /**
     * Barycentric Dynamic Time:the independent variable in planetay ephemerides; time at the solar system barycenter synchronous with TT on an annual basis; sometimes called TEB
     * 
     */
    TDB,

    /**
     * Barycentric Ephemeris Time: time at the solar system barycenter synchronous with TT on an annual basis; a deprecated synonym of TDB.
     * 
     */
    TEB,

    /**
     * Terrestrial Coordinate Time
     * 
     */
    TCG,

    /**
     * Barycentric Coordinate Time; runs slower than TDB but is consistent with physical constants
     * 
     */
    TCB,

    /**
     * International Atomic Time; runs 32.184 s behind TT
     * 
     */
    TAI,

    /**
     * Synonym for TAI
     * 
     */
    IAT,

    /**
     * Coordinated Universal Time; currently (2006) runs 33 leapseconds behind TAI
     * 
     */
    UTC,

    /**
     * Global Positioning System's time scale; runs 19 s behind TAI, 51.184 s behind TT.
     * 
     */
    GPS,

    /**
     * Local Siderial Time; only for ground-based observations; note that the second is shorter
     * 
     */
    LST,

    /**
     * Greenwich Mean Siderial Time; only for ground-based observations; note that the second is shorter
     * 
     */
    GMST,

    /**
     * Only to be used for simulations in conjunction with a relocatable spatial frame
     * 
     */
    LOCAL;

    public String value() {
        return name();
    }

    public static TimeScaleType fromValue(String v) {
        return valueOf(v);
    }

}
