//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 12:39:04 PM EST 
//


package au.csiro.casda.votools.jaxb.stc;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Single CError2, CResolution2, CSize2, CPixSize2 elements indicate definite values; pairs indicate ranges
 * 
 * <p>Java class for velVector2CoordinateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="velVector2CoordinateType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}posVector2CoordinateType">
 *       &lt;attribute name="vel_time_unit" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}velTimeUnitType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "velVector2CoordinateType")
public class VelVector2CoordinateType
    extends PosVector2CoordinateType
{

    @XmlAttribute(name = "vel_time_unit")
    protected VelTimeUnitType velTimeUnit;

    /**
     * Gets the value of the velTimeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link VelTimeUnitType }
     *     
     */
    public VelTimeUnitType getVelTimeUnit() {
        return velTimeUnit;
    }

    /**
     * Sets the value of the velTimeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link VelTimeUnitType }
     *     
     */
    public void setVelTimeUnit(VelTimeUnitType value) {
        this.velTimeUnit = value;
    }

}
