//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.12 at 01:03:24 PM EST 
//


package au.csiro.casda.votools.jaxb.vositables;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import au.csiro.casda.votools.jaxb.vodataservice.TableSet;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.csiro.casda.votools.jaxb.vositables package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Tableset_QNAME = new QName("http://www.ivoa.net/xml/VOSITables/v1.0", "tableset");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.csiro.casda.votools.jaxb.vositables
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of Tableset Object
     *
     */
    public Tableset createTableset() {
        return new Tableset();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TableSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOSITables/v1.0", name = "tableset")
    public JAXBElement<TableSet> createTableset(TableSet value) {
        return new JAXBElement<TableSet>(_Tableset_QNAME, TableSet.class, null, value);
    }

}
