//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.10 at 11:54:14 AM EST 
//


package au.csiro.casda.votools.jaxb.conesearch;

/*
 * #%L
 * CSIRO ASKAP Science Data Archive
 * %%
 * Copyright (C) 2015 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230.
 * %%
 * Licensed under the CSIRO Open Source License Agreement (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file.
 * #L%
 */


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import au.csiro.casda.votools.jaxb.voresource.Capability;


/**
 * 
 *             See vr:Capability for documentation on inherited children.
 *          
 * 
 * <p>Java class for CSCapRestriction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CSCapRestriction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.ivoa.net/xml/VOResource/v1.0}Capability">
 *       &lt;sequence>
 *         &lt;element name="validationLevel" type="{http://www.ivoa.net/xml/VOResource/v1.0}Validation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="interface" type="{http://www.ivoa.net/xml/VOResource/v1.0}Interface" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="standardID" use="required" type="{http://www.ivoa.net/xml/VOResource/v1.0}IdentifierURI" fixed="ivo://ivoa.net/std/ConeSearch" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CSCapRestriction")
@XmlSeeAlso({
    ConeSearch.class
})
public abstract class CSCapRestriction
    extends Capability
{


}
